version: '3.8'

services:
  nespro_url_shortener:
    image: postgres:alpine
    container_name: nespro_url_shortener
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '6543:5432'
    volumes:
      - nespro_url_shortener_data:/var/lib/postgresql/data

  nespro_url_shortener_redis:
    image: redis:alpine
    container_name: nespro_url_shortener_redis
    ports:
      - '6379:6379'
    volumes:
      - nespro_url_shortener_redis_data:/data

networks:
  default:
    name: nespro_url_shortener

volumes:
  nespro_url_shortener_data:
  nespro_url_shortener_redis_data:
