version: '3.8'

services:
  nest_starter_pg_prisma:
    image: postgres:alpine
    container_name: nest_starter_pg_prisma
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '6543:5432'
    volumes:
      - nest_starter_pg_prisma_data:/var/lib/postgresql/data

  nest_starter_pg_prisma_redis:
    image: redis:alpine
    container_name: nest_starter_pg_prisma_redis
    ports:
      - '6379:6379'
    volumes:
      - nest_starter_pg_prisma_redis_data:/data

networks:
  default:
    name: nest_starter_pg_prisma

volumes:
  nest_starter_pg_prisma_data:
  nest_starter_pg_prisma_redis_data:
